### ISSUE TITLE
[bug] animation-fill-mode 对translateX(200%) 以百分比为单位的不生效

### ISSUE THREAD

**Issue by deepkolos** [quickappcn/quickapp-dsl-vue#17]
`animation-fill-mode: forwards;`对于百分比单位的transform不生效, 在压入后台再切回前台的时候

![hap-animation-fill-mode-percent-bug](https://user-images.githubusercontent.com/12824616/58525951-1d9dc300-8200-11e9-937e-d9dda7aaea98.gif)

```css
.animated-x {
  animation-name: translateX;
  animation-delay: 1s;
  animation-duration: 1s;
  animation-fill-mode: forwards;
  transform: translateX(200%);
}

@keyframes translateX {
  0% {
    transform: translateX(200%);
  }
  100% {
    transform: translateX(0%);
  }
}
```

复现代码在
https://github.com/deepkolos/todomvc-vue/blob/master/src/pages/animation/index.vue#L19
